version: '3'
services:
  postgres_database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./.env_docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dilership/
    ports:
      - "8000:8080"
    env_file:
      - ./.env_docker
    depends_on:
      - postgres_database
      - redis

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/dilership/
    env_file:
      - ./.env_docker
    depends_on:
      - django
      - postgres_database
      - redis

  refresher:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/usr/src/dilership/
    env_file:
      - ./.env_docker
    depends_on:
      - celery
      - postgres_database
      - redis

volumes:
  postgres_data: