# Generated by Django 4.0.4 on 2022-06-26 17:02

import car_dealership.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_model', models.CharField(max_length=255, verbose_name='Car model')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarDealerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Dealership name')),
                ('country', django_countries.fields.CountryField(countries=car_dealership.models.G8Countries, max_length=2)),
                ('balance', models.FloatField(default=0, verbose_name='Dealership balance')),
            ],
            options={
                'verbose_name': 'AutoShow',
                'verbose_name_plural': 'AutoShows',
                'db_table': 'auto_show',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(blank=True, max_length=255, verbose_name='Car brand')),
                ('car_year', models.PositiveIntegerField(blank=True, default=None, verbose_name='Car year')),
                ('car_color', models.CharField(blank=True, max_length=255, verbose_name='Car color')),
                ('car_interior_color', models.CharField(blank=True, max_length=255, verbose_name='Car interior color')),
                ('car_mileage', models.IntegerField(blank=True, default=0, verbose_name='Car mileage')),
                ('car_body_type', models.CharField(blank=True, max_length=255, verbose_name='Car body type')),
                ('car_engine_type', models.CharField(blank=True, max_length=255, verbose_name='Car engine type')),
                ('car_engine_volume', models.FloatField(blank=True, default=None, verbose_name='Car engine volume')),
                ('car_gearbox', models.CharField(blank=True, choices=[('AUTO', 'Automatic'), ('SEMI', 'Semi-automatic'), ('MEC', 'Mechanical')], max_length=255, verbose_name='Car drive')),
                ('number_of_doors', models.PositiveIntegerField(blank=True, default=True, verbose_name='Number of doors')),
                ('VIN', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid Vehicle Number!', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Car VIN number')),
            ],
            options={
                'verbose_name': 'Car Information',
                'verbose_name_plural': 'Cars Information',
                'db_table': 'cars_information',
            },
        ),
        migrations.CreateModel(
            name='CarDealerShipHistorySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealership.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'AutoShow History Sales',
                'verbose_name_plural': 'AutoShows History Sales',
                'db_table': 'auto_show_history',
            },
        ),
    ]
