# Generated by Django 4.0.4 on 2022-06-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealer', '0001_initial'),
        ('car_dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealershiphistorysales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='cardealership',
            name='cars_list',
            field=models.ManyToManyField(related_name='dealership_car_list', to='car_dealership.car', verbose_name='Car list for auto_show'),
        ),
        migrations.AddField(
            model_name='cardealership',
            name='cars_sales_history',
            field=models.ManyToManyField(related_name='dealership_car_history_sales', to='car_dealership.cardealershiphistorysales', verbose_name='Car history sales'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_dealer',
            field=models.ManyToManyField(related_name='car_dealer', to='dealer.dealer', verbose_name='Car dealer'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_info', to='car_dealership.carinfo', verbose_name='Car information'),
        ),
    ]
