# Generated by Django 4.0.4 on 2022-07-01 09:03

from django.db import migrations, models
import src.customer.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercar',
            name='car_features',
        ),
        migrations.AddField(
            model_name='customer',
            name='car_features',
            field=models.JSONField(blank=True, default=src.customer.models.get_default_features, verbose_name='Car features'),
        ),
    ]
